# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: mycomputeragent

stages:
  - stage: Build
    jobs:  
    - job: FirstJob
      steps:
      - bash: echo Build FirstJob
    - job: SecondJob
      steps:
      - bash: echo Build SecondJob
  - stage: DevDeploy
    dependsOn: Build
    jobs:  
    - job: DevDeployJob
      steps:
      - bash: echo DevDeploy
  - stage: QADeploy
    dependsOn: Build
    jobs:
     - job: QADeployJob
       steps:
        - bash: echo QADeploy
  - stage: ProdDeploy
    dependsOn: 
     - DevDeploy
     - QADeploy
    jobs:
    - job: ProdDeployJob
      steps:
      - bash: echo ProdDeploy
